baseurl = "/"
languageCode = "en-us"
Title = "Stray Dog Strut"
theme="pickles"

# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright notice"

# Google Analytics API key.
googleAnalytics = "Your Google Analytics tracking id"

[params]
  mainSections = ["posts", "ghibli-review", "film-review"]
  custom_css = ["/css/custom.css"]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "Your Twitter username"
  instagram = "Your Instagram username"

  # Disqus shortname
  #disqus = ""
  #author = "Your Name"
  #authorwebsite = "example.com"
  #avatar = "/path/to/avatar"
  #contact = "Your contact link (ex. mailto:foo@example.com)"
  #bio = "Your short bio"

  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "barking up the wrong tree"
  # Logo image. This is displayed ogp image.
  logo = "/path/to/logo"
  favicon = "/path/to/favicon"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

    [[menu.main]]
        name = "Project Ghibli"
        url = "/ghibli-review"
        weight = 3

#[[menu.main]]
#    identifier = "theme"
#    name = "/theme"
#    weight = 3

#[[menu.main]]
#    parent = "theme"
#    name = "creating-a-new-theme"
#    url = "/posts/creating-a-new-theme"
#    weight = 1

#[[menu.main]]
#    parent = "theme"
#    name = "migrate-from-jekyll"
#    url = "/posts/migrate-from-jekyll"
#    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
